### ISSUE TITLE
Most recent docker update causing crashes to server (Unraid) running docker.

### ISSUE THREAD

**Issue by kagrith** [nsarrazin/serge#249]
### Bug description

Most recent update to docker image causes Unraid to Hang.
Have not yet had a chance to reproduce on LAB server.
Unfortunately i made the mistake of upgrading PROD first because i was hoping for performance uplift.
I believe i have eliminated everything else on the server, this is the only thing that seems to have changed.
The log output does not look complete, but its all i was able to extract.
Hope this helps!?

### Steps to reproduce

Step 0, Unraid 6.11.5, Let it get comfy, wait, for signs of stability.
Step 1, Start Docker Image for Serge with Most recent update on Unraid 6.11.5 
Step 1.5, Wait
Step 2, Before app loads, container hangs so hard it causes whole server lock forcing admin to cold shutdown

### Environment Information

Docker version 20.10.21, build baeda1f
OS: Unraid
OS Version: Unraid 6.11.5
CPU: Threadripper 1950x
RAM: 64GB

### Relevant log output

```shell
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/src/app/api/src/serge/main.py", line 10, in <module>
    from serge.routers.chat import chat_router
  File "/usr/local/lib/python3.11/site-packages/serge/routers/__init__.py", line 1, in <module>
    from .chat import chat_router
  File "/usr/local/lib/python3.11/site-packages/serge/routers/chat.py", line 5, in <module>
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'
Failed to build llama-cpp-python
123:C 28 Apr 2023 19:32:53.384 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
123:C 28 Apr 2023 19:32:53.384 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=123, just started
123:C 28 Apr 2023 19:32:53.384 # Configuration loaded
123:M 28 Apr 2023 19:32:53.384 * monotonic clock: POSIX clock_gettime
123:M 28 Apr 2023 19:32:53.384 * Running mode=standalone, port=6379.
123:M 28 Apr 2023 19:32:53.384 # Server initialized
123:M 28 Apr 2023 19:32:53.384 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
123:M 28 Apr 2023 19:32:53.386 * Reading RDB base file on AOF loading...
123:M 28 Apr 2023 19:32:53.386 * Loading RDB produced by version 7.0.11
123:M 28 Apr 2023 19:32:53.386 * RDB age 357998 seconds
123:M 28 Apr 2023 19:32:53.386 * RDB memory usage when created 0.82 Mb
123:M 28 Apr 2023 19:32:53.386 * RDB is base AOF
123:M 28 Apr 2023 19:32:53.386 * Done loading RDB, keys loaded: 0, keys expired: 0.
123:M 28 Apr 2023 19:32:53.386 * DB loaded from base file appendonly.aof.1.base.rdb: 0.000 seconds
123:M 28 Apr 2023 19:32:53.386 * DB loaded from incr file appendonly.aof.1.incr.aof: 0.001 seconds
123:M 28 Apr 2023 19:32:53.386 * DB loaded from append only file: 0.001 seconds
123:M 28 Apr 2023 19:32:53.387 * Opening AOF incr file appendonly.aof.1.incr.aof on server start
123:M 28 Apr 2023 19:32:53.387 * Ready to accept connections
Collecting llama-cpp-python
  Using cached llama_cpp_python-0.1.39.tar.gz (1.1 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.11/site-packages (from llama-cpp-python) (4.5.0)
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml): started
```

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by gaby** [comment]
@kagrith This was fix yesterday, can you pull the latest tag again?

**Comment by kagrith** [comment]
Tried pulling forcing update, mgmt shows no delta between image on hand and pulled image.
Backed up models, uninstalled, cleared DB, and pulled image fresh, gave it some time to setup, log shows clear.
Seems to be fine for now, aside from not being able to find its models. Not the end of the world.

**Comment by gaby** [comment]
@kagrith At least the vicuna models changed their named a few days ago, are those the ones you are using?

**Comment by kagrith** [comment]
Thats good to know, ill refresh those.
But the actual issue was my dumb ass manged to get whitespace chars into the directory name.
Fixed that, everything seems to be back to normal.

**Comment by kagrith** [comment]
Looks to be mostly back to normal.
Thanks for the sanity check!

**Comment by gaby** [comment]
Awesome!
