### ISSUE TITLE
Issue with /api/docs - server error

### ISSUE THREAD

**Issue by snxraven** [nsarrazin/serge#259]
### Bug description

Server error using "Try it out" for POST in Chat. 

Instead of the servers response from the AI we get a "Server Error"
  

### Steps to reproduce

Navigate to http://localhost:8008/api/docs#/chat/ask_a_question_chat__chat_id__question_post

Run a request to a chat ID with chat posting to the API.

Get error.

### Environment Information

Standard Docker
Docker version 23.0.3, build 3e7cbfd

### Screenshots

![image](https://user-images.githubusercontent.com/1396275/235711859-f8c1ba7f-a21b-49b7-895b-0d4097cf8a51.png)

### Relevant log output

```shell
llama_model_load_internal: mem required  = 9807.56 MB (+ 1608.00 MB per state)
llama_init_from_file: kv self size  =  400.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 1 | AVX512_VNNI = 1 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 
llama_print_timings:        load time =  6652.89 ms
llama_print_timings:      sample time =     5.39 ms /     9 runs   (    0.60 ms per run)
llama_print_timings: prompt eval time =  6652.85 ms /    48 tokens (  138.60 ms per token)
llama_print_timings:        eval time =  1904.38 ms /     8 runs   (  238.05 ms per run)
llama_print_timings:       total time =  8563.56 ms
INFO:     172.17.0.1:47420 - "POST /chat/2424af64-773a-4585-85f6-8a2810f7c548/question?prompt=Hello HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 109, in __call__
    await response(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 134, in stream_response
    return await super().stream_response(send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 98, in body_stream
    raise app_exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/serge/routers/chat.py", line 248, in ask_a_question
    history.add_ai_message(answer)
  File "/usr/local/lib/python3.11/site-packages/langchain/memory/chat_message_histories/redis.py", line 59, in add_ai_message
    self.append(AIMessage(content=message))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AIMessage
content
  str type expected (type=type_error.str)
INFO:     172.17.0.1:57980 - "GET /chat/2424af64-773a-4585-85f6-8a2810f7c548 HTTP/1.1" 200 OK
INFO:     172.17.0.1:57980 - "GET /chat/ HTTP/1.1" 200 OK
INFO:     172.17.0.1:57980 - "GET /chat/2424af64-773a-4585-85f6-8a2810f7c548 HTTP/1.1" 200 OK
```

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by toasterrepairman** [comment]
I'm getting this too. Running on an Ampere server, noticed it a week or two ago when my API calls started 500ing. I've had success making new chats and seemingly generating text, but the API fails when it's time to respond to the POST request. 

I would post my docker logs, but they look the exact same as OP's.

**Comment by Kastakin** [comment]
Same issue here.

The UI works just fine.
The POST route always return an Internal Server Error with the above message. The GET question route works fine but of course the streaming response is quite an inconvenience to work with.

As reported @toasterrepairman I would post my docker log but it is the exact same as the one posted by @snxraven

**Comment by odieXin** [comment]
Any update on this bug?

**Comment by Dominik-Notzon** [comment]
I've got the same problem. Right now the API is basically not usable sadly.

**Comment by gaby** [comment]
I'm looking into this issue

**Comment by gaby** [comment]
@snxraven @odieXin @Kastakin @Kastakin @nsarrazin Fix has bedn pushed. It's available using the `main` tag until a new release is done. 

```
docker pull ghcr.io/nsarrazin/serge:main
```
