### ISSUE TITLE
Connection error when downloading models from huggingface

### ISSUE THREAD

**Issue by hmassareli** [nsarrazin/serge#55]
When I run docker compose exec api python3 /usr/src/app/utils/download.py tokenizer 30B, the following error appears in a certain point of the installation:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 444, in _error_catcher
    yield
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 567, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 533, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/usr/lib/python3.10/http/client.py", line 465, in read
    s = self.fp.read(amt)
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 628, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 566, in read
    with self._error_catcher():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 449, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/utils/download.py", line 53, in <module>
    download_models(args.model)
  File "/usr/src/app/utils/download.py", line 35, in download_models
    huggingface_hub.hf_hub_download(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 1326, in hf_hub_download
    http_get(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 538, in http_get
    for chunk in r.iter_content(chunk_size=10 * 1024 * 1024):
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 822, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.
```

**Comment by hmassareli** [comment]
Is there maybe a way of downloading the model manually?

**Comment by Dwel** [comment]
When I run 'docker compose exec api python3 /usr/src/app/utils/download.py tokenizer 30B'

I get
"C:\Users\Dwel>docker compose exec api python3 /usr/src/app/utils/download.py tokenizer 7B
no configuration file provided: not found"

**Comment by nsarrazin** [comment]
> When I run 'docker compose exec api python3 /usr/src/app/utils/download.py tokenizer 30B'
> 
> I get "C:\Users\Dwel>docker compose exec api python3 /usr/src/app/utils/download.py tokenizer 7B no configuration file provided: not found"

I think your version is quite out of date, there's no download.py file anymore. Feel free to pull the latest changes and check the readme. Should be a lot easier to get models now.

**Comment by Dwel** [comment]
Your response was quicker than my edit. Everything was installed fresh today.
Docker is v4.17.1
Python is 3.11.2
