### ISSUE TITLE
EMFILE: too many open files, watch '/usr/src/app/web/vite.config.ts'

### ISSUE THREAD

**Issue by voarsh2** [nsarrazin/serge#75]
### Bug description

Error: EMFILE: too many open files, watch '/usr/src/app/web/vite.config.ts' is presented, but the host system and docker container has a limit of 1048576

### Steps to reproduce

Deploy YAML on K8 cluster:
https://github.com/nsarrazin/serge/wiki/Integrating-Serge-in-your-orchestration#kubernetes-example

### Environment Information

Docker image: ghcr.io/nsarrazin/serge:release
Containrd
OS Linux Ubuntu 22.04 LTS
CPU: 48 x Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz (2 Sockets)

### Relevant log output

```shell
> web@0.0.1 dev
> vite dev --host 0.0.0.0 --port 8008
INFO: Started server process [12]
INFO: Waiting for application startup.
INFO: main initializing database connection
▲ [WARNING] Cannot find base config file "./.svelte-kit/tsconfig.json" [tsconfig.json]
tsconfig.json:2:12:
2 │ "extends": "./.svelte-kit/tsconfig.json",
╵ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node:internal/errors:490
ErrorCaptureStackTrace(err);
^
Error: EMFILE: too many open files, watch '/usr/src/app/web/vite.config.ts'
at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
at Object.watch (node:fs:2350:36)
at createFsWatchInstance (file:///usr/src/app/web/node_modules/vite/dist/node/chunks/dep-c167897e.js:50313:17)
at setFsWatchListener (file:///usr/src/app/web/node_modules/vite/dist/node/chunks/dep-c167897e.js:50360:15)
at NodeFsHandler._watchWithNodeFs (file:///usr/src/app/web/node_modules/vite/dist/node/chunks/dep-c167897e.js:50515:14)
at NodeFsHandler._handleFile (file:///usr/src/app/web/node_modules/vite/dist/node/chunks/dep-c167897e.js:50579:23)
at NodeFsHandler._addToNodeFs (file:///usr/src/app/web/node_modules/vite/dist/node/chunks/dep-c167897e.js:50821:21)
at async file:///usr/src/app/web/node_modules/vite/dist/node/chunks/dep-c167897e.js:51817:21
at async Promise.all (index 1)
Emitted 'error' event on FSWatcher instance at:
at FSWatcher._handleError (file:///usr/src/app/web/node_modules/vite/dist/node/chunks/dep-c167897e.js:52013:10)
at NodeFsHandler._addToNodeFs (file:///usr/src/app/web/node_modules/vite/dist/node/chunks/dep-c167897e.js:50829:18)
at async file:///usr/src/app/web/node_modules/vite/dist/node/chunks/dep-c167897e.js:51817:21
at async Promise.all (index 1) {
errno: -24,
syscall: 'watch',
code: 'EMFILE',
path: '/usr/src/app/web/vite.config.ts',
filename: '/usr/src/app/web/vite.config.ts'
}
Node.js v19.8.1
```
```


### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by voarsh2** [comment]
Issue not present when running ghcr.io/nsarrazin/serge:0.0
