### ISSUE TITLE
TypeError: fetch failed

### ISSUE THREAD

**Issue by dyno** [nsarrazin/serge#85]
### Bug description

follow the step to bring up the service, but it cannot recognize the downloaded model. from the console, i can see error like

```
TypeError: fetch failed
    at fetch (/usr/src/app/web/node_modules/undici/index.js:109:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:405:11)
    at async Module.respond (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:240:20)
    at async fetch (/node_modules/@sveltejs/kit/src/runtime/server/fetch.js:134:16)
    at async Object.eval [as fetch] (/node_modules/@sveltejs/kit/src/runtime/server/fetch.js:27:10)
    at async eval (/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:195:18)
    at async load (+page.ts:4:12)
    at async Module.load_data (/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:162:17)
    at async eval (/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:169:13)
```

### Steps to reproduce

```
docker compose up 
docker compose exec serge python3 /usr/src/app/api/utils/download.py tokenizer 7B
```

### Environment Information

```
                    'c.          
                 ,xNMM.          -----------------------------------
               .OMMMMo           OS: macOS 13.2.1 22D68 x86_64
               OMMM0,            Host: MacBookPro16,1
     .;loddo:' loolloddol;.      Kernel: 22.3.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 22 days, 23 hours, 45 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 266 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: bash 5.2.15
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1792x1120@2x, 3440x1440@2x, 1920x1080@2x
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Rectangle
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    Terminal: tmux
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   CPU: Intel i9-9980HK (16) @ 2.40GHz
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   GPU: Intel UHD Graphics 630, AMD Radeon Pro 5500M
    kMMMMMMMMMMMMMMMMMMMMMMd     Memory: 37772MiB / 65536MiB
     ;KMMMMMMMWXXWMMMMMMMk.
       .cooc,.    .,coo:.
```

### Relevant log output

```shell
in the bug description.
```

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by choseh** [comment]
same here, happens with 30B aswell, just fyi

**Comment by nsarrazin** [comment]
Can you try again with the latest version of main ? Pushed some stuff that could fix this.

**Comment by nsarrazin** [comment]
@choseh  The images just landed in the registry! Feel free to give it a shot.

**Comment by choseh** [comment]
ah my bad, after another `docker compose up --build` it's fine now. I was expecting to find the images in an actual repo ;)
